In [30]:
import pandas as pd

In [31]:
chicago = pd.read_csv('csv_files/chicago.csv', index_col='Name').dropna(how = 'all')
chicago.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [32]:
chicago.info()

<class 'pandas.DataFrame'>
Index: 32062 entries, AARON,  ELVIA J to ZYSKOWSKI,  DARIUSZ
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Position Title          32062 non-null  str
 1   Department              32062 non-null  str
 2   Employee Annual Salary  32062 non-null  str
dtypes: str(3)
memory usage: 1001.9+ KB

In [33]:
print(f"Unique Values: {chicago['Department'].nunique()}, Count: {chicago["Department"].count()}")

Unique Values: 35, Count: 32062

In [34]:
chicago['Department'] = chicago['Department'].astype('category')
chicago.info()

<class 'pandas.DataFrame'>
Index: 32062 entries, AARON,  ELVIA J to ZYSKOWSKI,  DARIUSZ
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Position Title          32062 non-null  str
 1   Department              32062 non-null  category
 2   Employee Annual Salary  32062 non-null  str
dtypes: category(1), str(2)
memory usage: 783.0+ KB

String Method-> lower, upper, title, len

In [35]:
'hello world'.title()

'Hello World'

In [36]:
chicago['Position Title'] = chicago['Position Title'].str.title()
chicago.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"AARON, ELVIA J",Water Rate Taker,WATER MGMNT,$90744.00
"AARON, JEFFERY M",Police Officer,POLICE,$84450.00
"AARON, KARINA",Police Officer,POLICE,$84450.00
"AARON, KIMBERLEI R",Chief Contract Expediter,GENERAL SERVICES,$89880.00
"ABAD JR, VICENTE M",Civil Engineer Iv,WATER MGMNT,$106836.00

In [37]:
chicago['Department'] = chicago['Department'].str.replace('MGMNT', 'MANAGEMENT')

In [38]:
chicago['Employee Annual Salary'] = chicago['Employee Annual Salary'].str.replace('$', '').astype(float)

In [39]:
chicago['Employee Annual Salary'].mean()

np.float64(80204.17863389681)

In [40]:
mask = chicago['Position Title'].str.lower().str.contains('water') #startswith same functionality
mask2 = chicago['Position Title'].str.lower().str.startswith('water') #startswith same functionality
mask3 = chicago['Position Title'].str.lower().str.endswith('ist') #startswith same functionality


chicago[mask]
chicago[mask2]
chicago[mask3]

,Position Title,Department,Employee Annual Salary
Name,,,
"AFROZ, NAYYAR",Psychiatrist,HEALTH,99840.0
"ALARCON, LUIS J",Loan Processing Specialist,COMMUNITY DEVELOPMENT,81948.0
"ALLAIN, CAROLYN",Senior Telecommunications Specialist,DoIT,89880.0
"ALLEN, ROBERT",Machinist,WATER MANAGEMENT,94328.0
"ANDERSON, EDWARD M",Sr Procurement Specialist,PROCUREMENT,91476.0
...,...,...,...
"YODER, TERESA G",Archival Specialist,PUBLIC LIBRARY,74304.0
"YOUNGBLOOM, LAURENCE G",Crimes Surveillance Specialist,OEMC,19676.8
"YOUNG, KIMBERLY M",Sr Procurement Specialist,PROCUREMENT,68556.0
"ZAPATA, HUGO",Sr Procurement Specialist,PROCUREMENT,87324.0
"ZEMKE, RICHARD P",Machinist,AVIATION,94328.0

name.strip()	"James Bond"	Removed spaces from both ends.
name.lstrip()	"James Bond "	Removed spaces from the left only.
name.rstrip()	" James Bond"	Removed spaces from the right only.

In [41]:
print("        Hello World".strip())
print("        Hello World".strip())

Hello World
Hello World

In [44]:
chicago.index = chicago.index.str.strip().str.title()
chicago.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"Aaron, Elvia J",Water Rate Taker,WATER MANAGEMENT,90744.0
"Aaron, Jeffery M",Police Officer,POLICE,84450.0
"Aaron, Karina",Police Officer,POLICE,84450.0
"Aaron, Kimberlei R",Chief Contract Expediter,GENERAL SERVICES,89880.0
"Abad Jr, Vicente M",Civil Engineer Iv,WATER MANAGEMENT,106836.0

In [46]:
chicago.columns = chicago.columns.str.upper()
chicago.head()

,POSITION TITLE,DEPARTMENT,EMPLOYEE ANNUAL SALARY
Name,,,
"Aaron, Elvia J",Water Rate Taker,WATER MANAGEMENT,90744.0
"Aaron, Jeffery M",Police Officer,POLICE,84450.0
"Aaron, Karina",Police Officer,POLICE,84450.0
"Aaron, Kimberlei R",Chief Contract Expediter,GENERAL SERVICES,89880.0
"Abad Jr, Vicente M",Civil Engineer Iv,WATER MANAGEMENT,106836.0

Split

In [47]:
"Hello my name is Saswat".split(' ')

['Hello', 'my', 'name', 'is', 'Saswat']

In [51]:
chicago.index.str.split(',').str.get(0).value_counts()

Name
Williams     293
Johnson      244
Smith        241
Brown        185
Jones        183
            ...
Zydek          1
Zygowicz       1
Zymantas       1
Zyrkowski      1
Zyskowski      1
Name: count, Length: 13829, dtype: int64

In [ ]:
chicago['POSITION TITLE'].str.split(' ').str.get(0).value_counts() # in split we can also assign n value which states how many data to split

POSITION TITLE
Police             10856
Firefighter-Emt     1509
Sergeant            1186
Pool                 918
Firefighter          810
                   ...
Comm                   1
Equal                  1
Hate                   1
Deck                   1
Prepress               1
Name: count, Length: 320, dtype: int64