In [3]:
import pandas as pd

In [53]:
nba = pd.read_csv('csv_files/nba.csv')

In [7]:
nba.head()
nba.index

RangeIndex(start=0, stop=458, step=1)

In [8]:
nba.shape

(458, 9)

In [9]:
nba.dtypes

Name            str
Team            str
Number      float64
Position        str
Age         float64
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [10]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='str')

In [12]:
nba.axes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='str')]

In [13]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   373 non-null    str
 8   Salary    446 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB

In [15]:
nba.dtypes.value_counts()

str        5
float64    4
Name: count, dtype: int64

In [17]:
rev = pd.read_csv('csv_files/revenue.csv', index_col='Date')
rev.head()

        New York  Los Angeles  Miami
Date
1/1/16       985          122    499
1/2/16       738          788    534
1/3/16        14           20    933
1/4/16       730          904    885
1/5/16       114           71    253

In [20]:
rev.sum(axis=1)

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

Extract Column-> output becomes a series

In [ ]:
#One way
nba_column_series = nba.Name
Output=None
#Best way
nba["Name"]

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: str

In [ ]:
nba[["Name", "Team"]] #this becomes a dataframe not a series
#best approach
select = ["Name", "Team", "Salary"]
nba[select]

              Name            Team     Salary
0    Avery Bradley  Boston Celtics  7730337.0
1      Jae Crowder  Boston Celtics  6796117.0
2     John Holland  Boston Celtics        NaN
3      R.J. Hunter  Boston Celtics  1148640.0
4    Jonas Jerebko  Boston Celtics  5000000.0
..             ...             ...        ...
453   Shelvin Mack       Utah Jazz  2433333.0
454      Raul Neto       Utah Jazz   900000.0
455   Tibor Pleiss       Utah Jazz  2900000.0
456    Jeff Withey       Utah Jazz   947276.0
457            NaN             NaN        NaN

[458 rows x 3 columns]

In [ ]:
#Add Column
nba["Sport"] = "Basketball"
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,Basketball
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,Basketball
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,Basketball
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball

In [ ]:
nba.insert(3, column="Sport", value = "Basket")

ValueError: cannot insert Sport, already exists

In [33]:
nba

,Name,Team,Number,Sport,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,Basket,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,Basket,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,Basket,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,Basket,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,Basket,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,Basket,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,Basket,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,Basket,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,Basket,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,Basket,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
#Adds 5 to every 'Age' column
nba["Age"].add(5)
nba["Age"] + 5
nba["Weight in kgs"] = nba['Weight'] * 0.453592

In [39]:
nba

,Name,Team,Number,Sport,Position,Age,Height,Weight,College,Salary,Weight in kgs
0,Avery Bradley,Boston Celtics,0.0,Basket,PG,25.0,6-2,180.0,Texas,7730337.0,81.646560
1,Jae Crowder,Boston Celtics,99.0,Basket,SF,25.0,6-6,235.0,Marquette,6796117.0,106.594120
2,John Holland,Boston Celtics,30.0,Basket,SG,27.0,6-5,205.0,Boston University,NaN,92.986360
3,R.J. Hunter,Boston Celtics,28.0,Basket,SG,22.0,6-5,185.0,Georgia State,1148640.0,83.914520
4,Jonas Jerebko,Boston Celtics,8.0,Basket,PF,29.0,6-10,231.0,NaN,5000000.0,104.779752
...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,Basket,PG,26.0,6-3,203.0,Butler,2433333.0,92.079176
454,Raul Neto,Utah Jazz,25.0,Basket,PG,24.0,6-1,179.0,NaN,900000.0,81.192968
455,Tibor Pleiss,Utah Jazz,21.0,Basket,C,26.0,7-3,256.0,NaN,2900000.0,116.119552
456,Jeff Withey,Utah Jazz,24.0,Basket,C,26.0,7-0,231.0,Kansas,947276.0,104.779752
457,NaN,NaN,NaN,Basket,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
#Find common data like most popular and least popular
nba["Position"].value_counts()
nba["Salary"].value_counts().head()

Salary
947276.0     31
845059.0     18
525093.0     13
981348.0      6
5000000.0     5
Name: count, dtype: int64

In [44]:
#drops values with null values
nba.dropna()
#drop values where all the columns have null values
nba.dropna(how = "all", inplace=True)

In [ ]:
#drops value where specific column value is null
nba.dropna(subset=['Salary'])

,Name,Team,Number,Sport,Position,Age,Height,Weight,College,Salary,Weight in kgs
0,Avery Bradley,Boston Celtics,0.0,Basket,PG,25.0,6-2,180.0,Texas,7730337.0,81.646560
1,Jae Crowder,Boston Celtics,99.0,Basket,SF,25.0,6-6,235.0,Marquette,6796117.0,106.594120
3,R.J. Hunter,Boston Celtics,28.0,Basket,SG,22.0,6-5,185.0,Georgia State,1148640.0,83.914520
4,Jonas Jerebko,Boston Celtics,8.0,Basket,PF,29.0,6-10,231.0,NaN,5000000.0,104.779752
5,Amir Johnson,Boston Celtics,90.0,Basket,PF,29.0,6-9,240.0,NaN,12000000.0,108.862080
...,...,...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,Basket,PF,20.0,6-10,234.0,Kentucky,2239800.0,106.140528
453,Shelvin Mack,Utah Jazz,8.0,Basket,PG,26.0,6-3,203.0,Butler,2433333.0,92.079176
454,Raul Neto,Utah Jazz,25.0,Basket,PG,24.0,6-1,179.0,NaN,900000.0,81.192968
455,Tibor Pleiss,Utah Jazz,21.0,Basket,C,26.0,7-3,256.0,NaN,2900000.0,116.119552
456,Jeff Withey,Utah Jazz,24.0,Basket,C,26.0,7-0,231.0,Kansas,947276.0,104.779752

In [ ]:
#fills null value
nba.fillna(0)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,0,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,0,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,0,0,0.0,0,0.0,0,0.0,0,0.0

In [ ]:
#specific column's null value assignment
nba.fillna({"Salary": 0, "College" : "No College"}, inplace=True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,No College,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,No College,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,No College,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No College,0.0

In [61]:
nba["Salary"] = nba["Salary"].astype('int')
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   458 non-null    str
 8   Salary    458 non-null    int64
dtypes: float64(3), int64(1), str(5)
memory usage: 32.3 KB

Store as categories for better memory usage

In [63]:
nba["Team"].nunique()

30

In [64]:
nba["Team"] = nba["Team"].astype("category")

In [ ]:
#memory usage decreases
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    category
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   458 non-null    str
 8   Salary    458 non-null    int64
dtypes: category(1), float64(3), int64(1), str(4)
memory usage: 29.4 KB

In [71]:
#nba.sort_values('Salary')
#multi columns
#first sorts by Team then sorts by Name
select_filters = ["Team", "Name"]
nba.sort_values(select_filters)
nba.sort_values(select_filters, ascending=[True,False], inplace=True) #use ascending for 1 and not other value

In [73]:
nba.sort_index()
nba.sort_index(ascending=False, inplace=True)

In [74]:
nba.head(4)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No College,0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,No College,2900000
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,No College,900000

Ranks
In data analysis, the .rank() function is like a judge at a competition: it looks at a list of numbers and assigns each one a position (1st, 2nd, 3rd, etc.) based on its value relative to the others.

In [75]:
nba = pd.read_csv('csv_files/nba.csv').dropna(how='all')
nba['Salary'] = nba['Salary'].fillna(0).astype('int')
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000

In [77]:
nba['Salary Rank'] = nba['Salary'].rank(ascending=False)

In [79]:
nba.sort_values(by='Salary', ascending=False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary Rank
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000,1.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500,2.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000,3.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364,4.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730,5.0
...,...,...,...,...,...,...,...,...,...,...
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,0,452.0
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,0,452.0
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,0,452.0
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,0,452.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0,452.0