In [1]:
import pandas as pd

In [2]:
bigmac = pd.read_csv('csv_files/bigmac.csv', parse_dates=['Date'], date_format='%Y-%m-%d')
bigmac.head()

     Date    Country  Price in US Dollars
0  1/2016  Argentina                 2.39
1  1/2016  Australia                 3.74
2  1/2016     Brazil                 3.35
3  1/2016    Britain                 4.22
4  1/2016     Canada                 4.14

In [3]:
bigmac.set_index(keys=['Date', 'Country'], inplace=True) #outer layer should be the first, and larger should be second layer and so on

In [4]:
bigmac.sort_index(inplace=True)

In [5]:
type(bigmac.index)

pandas.MultiIndex

In [6]:
bigmac.index[0]

('1/2010', 'Argentina')

In [7]:
bigmac.index.get_level_values('Date')

Index(['1/2010', '1/2010', '1/2010', '1/2010', '1/2010', '1/2010', '1/2010',
       '1/2010', '1/2010', '1/2010',
       ...
       '7/2015', '7/2015', '7/2015', '7/2015', '7/2015', '7/2015', '7/2015',
       '7/2015', '7/2015', '7/2015'],
      dtype='str', name='Date', length=652)

In [8]:
bigmac.index.set_names(['Day', 'Location'], inplace=True)

In [9]:
bigmac.head()

                  Price in US Dollars
Day    Location
1/2010 Argentina                 1.84
       Australia                 3.98
       Brazil                    4.76
       Britain                   3.67
       Canada                    3.97

Extract Rows from MultiIndex

In [10]:
bigmac.loc[('1/2010', 'Brazil'), 'Price in US Dollars'] #key then the column value wanted to be extracted

np.float64(4.76)

In [11]:
bigmac = bigmac.transpose()

In [12]:
bigmac.loc['Price in US Dollars', ('1/2016', 'China')]

np.float64(2.68)

In [13]:
bigmac = pd.read_csv('csv_files/bigmac.csv', parse_dates=['Date'], date_format='%Y-%m-%d', index_col=['Date', 'Country'])
bigmac.sort_index(inplace=True)
bigmac.head()

                  Price in US Dollars
Date   Country
1/2010 Argentina                 1.84
       Australia                 3.98
       Brazil                    4.76
       Britain                   3.67
       Canada                    3.97

In [14]:
bigmac.swaplevel() #swaps index places

                      Price in US Dollars
Country       Date
Argentina     1/2010                 1.84
Australia     1/2010                 3.98
Brazil        1/2010                 4.76
Britain       1/2010                 3.67
Canada        1/2010                 3.97
...                                   ...
Ukraine       7/2015                 1.55
United States 7/2015                 4.79
Uruguay       7/2015                 4.13
Venezuela     7/2015                 0.67
Vietnam       7/2015                 2.75

[652 rows x 1 columns]

The .stack() Method

In [17]:
world = pd.read_csv('csv_files/worldstats.csv', index_col = ['country', 'year'])
world.head(3)

                  Population           GDP
country    year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12

In [18]:
world.stack()

country     year
Arab World  2015  Population    3.920223e+08
                  GDP           2.530102e+12
            2014  Population    3.842226e+08
                  GDP           2.873600e+12
            2013  Population    3.765043e+08
                                    ...
Zimbabwe    1962  GDP           1.117602e+09
            1961  Population    3.876638e+06
                  GDP           1.096647e+09
            1960  Population    3.752390e+06
                  GDP           1.052990e+09
Length: 22422, dtype: float64

In [19]:
world.stack().to_frame()

                                       0
country    year
Arab World 2015 Population  3.920223e+08
                GDP         2.530102e+12
           2014 Population  3.842226e+08
                GDP         2.873600e+12
           2013 Population  3.765043e+08
...                                  ...
Zimbabwe   1962 GDP         1.117602e+09
           1961 Population  3.876638e+06
                GDP         1.096647e+09
           1960 Population  3.752390e+06
                GDP         1.052990e+09

[22422 rows x 1 columns]

In [22]:
s = world.stack()
s.unstack().unstack().unstack()

            year  country
Population  1960  Afghanistan           8.994793e+06
                  Albania                        NaN
                  Algeria               1.112489e+07
                  Andorra                        NaN
                  Angola                         NaN
                                            ...
GDP         2015  West Bank and Gaza    1.267740e+10
                  World                 7.343364e+13
                  Yemen, Rep.                    NaN
                  Zambia                2.120156e+10
                  Zimbabwe              1.389294e+10
Length: 28224, dtype: float64

In [ ]:
s.unstack(1) #index level

year                            1960          1961          1962  \
country
Afghanistan Population  8.994793e+06  9.164945e+06  9.343772e+06
            GDP         5.377778e+08  5.488889e+08  5.466667e+08
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.112489e+07  1.140486e+07  1.169015e+07
...                              ...           ...           ...
Yemen, Rep. GDP                  NaN           NaN           NaN
Zambia      Population  3.049586e+06  3.142848e+06  3.240664e+06
            GDP         6.987397e+08  6.823597e+08  6.792797e+08
Zimbabwe    Population  3.752390e+06  3.876638e+06  4.006262e+06
            GDP         1.052990e+09  1.096647e+09  1.117602e+09

year                            1963          1964          1965  \
country
Afghanistan Population  9.531555e+06  9.728645e+06  9.935358e+06
            GDP         7.511112e+08  8.000000e+08  1.006667e+09
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.198513e+07  1.229597e+07  1.262695e+07
...                              ...           ...           ...
Yemen, Rep. GDP                  NaN           NaN           NaN
Zambia      Population  3.342894e+06  3.449266e+06  3.559687e+06
            GDP         7.043397e+08  8.226397e+08  1.061200e+09
Zimbabwe    Population  4.140804e+06  4.279561e+06  4.422132e+06
            GDP         1.159512e+09  1.217138e+09  1.311436e+09

year                            1966          1967          1968  \
country
Afghanistan Population  1.014884e+07  1.036860e+07  1.059979e+07
            GDP         1.400000e+09  1.673333e+09  1.373333e+09
Albania     Population           NaN           NaN           NaN
            GDP                  NaN           NaN           NaN
Algeria     Population  1.298027e+07  1.335420e+07  1.374438e+07
...                              ...           ...           ...
Yemen, Rep. GDP                  NaN           NaN           NaN
Zambia      Population  3.674088e+06  3.792864e+06  3.916928e+06
            GDP         1.239000e+09  1.340639e+09  1.573739e+09
Zimbabwe    Population  4.568320e+06  4.718612e+06  4.874113e+06
            GDP         1.281750e+09  1.397002e+09  1.479600e+09

year                            1969  ...          2006          2007  \
country                               ...
Afghanistan Population  1.084951e+07  ...  2.518362e+07  2.587754e+07
            GDP         1.408889e+09  ...  7.057598e+09  9.843842e+09
Albania     Population           NaN  ...  2.992547e+06  2.970017e+06
            GDP                  NaN  ...  8.992642e+09  1.070101e+10
Algeria     Population  1.414444e+07  ...  3.374933e+07  3.426197e+07
...                              ...  ...           ...           ...
Yemen, Rep. GDP                  NaN  ...  1.908173e+10  2.563367e+10
Zambia      Population  4.047479e+06  ...  1.238151e+07  1.273868e+07
            GDP         1.926399e+09  ...  1.275686e+10  1.405696e+10
Zimbabwe    Population  5.036321e+06  ...  1.312794e+07  1.329780e+07
            GDP         1.747999e+09  ...  5.443896e+09  5.291950e+09

year                            2008          2009          2010  \
country
Afghanistan Population  2.652874e+07  2.720729e+07  2.796221e+07
            GDP         1.019053e+10  1.248694e+10  1.593680e+10
Albania     Population  2.947314e+06  2.927519e+06  2.913021e+06
            GDP         1.288135e+10  1.204421e+10  1.192695e+10
Algeria     Population  3.481106e+07  3.540179e+07  3.603616e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.039720e+10  2.845950e+10  3.090675e+10
Zambia      Population  1.311458e+07  1.350785e+07  1.391744e+07
            GDP         1.791086e+10  1.532834e+10  2.026555e+10
Zimbabwe    Population  1.349546e+07  1.372100e+07  1.397390e+07
            GDP         4.415703e+09  8.157077e+09  9.422161e+09

year                            2011          2012          2013  \
country
Afghanistan Population  2.880917e+07  2.972680e+07  3.068250e+07
            GDP         1.793024e+10  2.053654e+10  2.004633e+10
Albania     Population  2.904780e+06  2.900247e+06  2.896652e+06
            GDP         1.289087e+10  1.231978e+10  1.278103e+10
Algeria     Population  3.671713e+07  3.743943e+07  3.818614e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.107886e+10  3.207477e+10  3.595450e+10
Zambia      Population  1.434353e+07  1.478658e+07  1.524609e+07
            GDP         2.345952e+10  2.550306e+10  2.804552e+10
Zimbabwe    Population  1.425559e+07  1.456548e+07  1.489809e+07
            GDP         1.095623e+10  1.239272e+10  1.349023e+10

year                            2014          2015
country
Afghanistan Population  3.162751e+07  3.252656e+07
            GDP         2.005019e+10  1.919944e+10
Albania     Population  2.893654e+06  2.889167e+06
            GDP         1.327796e+10  1.145560e+10
Algeria     Population  3.893433e+07  3.966652e+07
...                              ...           ...
Yemen, Rep. GDP                  NaN           NaN
Zambia      Population  1.572134e+07  1.621177e+07
            GDP         2.713464e+10  2.120156e+10
Zimbabwe    Population  1.524586e+07  1.560275e+07
            GDP         1.419691e+10  1.389294e+10

[504 rows x 56 columns]

In [ ]:
s.unstack(-1)

                  Population           GDP
country     year
Afghanistan 1960   8994793.0  5.377778e+08
            1961   9164945.0  5.488889e+08
            1962   9343772.0  5.466667e+08
            1963   9531555.0  7.511112e+08
            1964   9728645.0  8.000000e+08
...                      ...           ...
Zimbabwe    2011  14255592.0  1.095623e+10
            2012  14565482.0  1.239272e+10
            2013  14898092.0  1.349023e+10
            2014  15245855.0  1.419691e+10
            2015  15602751.0  1.389294e+10

[11211 rows x 2 columns]

In [29]:
s.unstack('country')

country           Afghanistan       Albania       Algeria       Andorra  \
year
1960 Population  8.994793e+06           NaN  1.112489e+07           NaN
     GDP         5.377778e+08           NaN  2.723638e+09           NaN
1961 Population  9.164945e+06           NaN  1.140486e+07           NaN
     GDP         5.488889e+08           NaN  2.434767e+09           NaN
1962 Population  9.343772e+06           NaN  1.169015e+07           NaN
...                       ...           ...           ...           ...
2013 GDP         2.004633e+10  1.278103e+10  2.097035e+11  3.249101e+09
2014 Population  3.162751e+07  2.893654e+06  3.893433e+07           NaN
     GDP         2.005019e+10  1.327796e+10  2.135185e+11           NaN
2015 Population  3.252656e+07  2.889167e+06  3.966652e+07           NaN
     GDP         1.919944e+10  1.145560e+10  1.668386e+11           NaN

country                Angola  Antigua and Barbuda    Arab World  \
year
1960 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1961 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1962 Population           NaN                  NaN           NaN
...                       ...                  ...           ...
2013 GDP         1.249121e+11         1.200588e+09  2.846994e+12
2014 Population  2.422752e+07         9.090000e+04  3.842226e+08
     GDP         1.267751e+11         1.220976e+09  2.873600e+12
2015 Population  2.502197e+07         9.181800e+04  3.920223e+08
     GDP         1.026431e+11         1.297285e+09  2.530102e+12

country             Argentina       Armenia  Aruba  ...    Uzbekistan  \
year                                                ...
1960 Population           NaN           NaN    NaN  ...           NaN
     GDP                  NaN           NaN    NaN  ...           NaN
1961 Population           NaN           NaN    NaN  ...           NaN
     GDP                  NaN           NaN    NaN  ...           NaN
1962 Population  2.128768e+07           NaN    NaN  ...           NaN
...                       ...           ...    ...  ...           ...
2013 GDP         6.239320e+11  1.112147e+10    NaN  ...  5.679566e+10
2014 Population  4.298003e+07  3.006154e+06    NaN  ...  3.075770e+07
     GDP         5.480549e+11  1.164444e+10    NaN  ...  6.313285e+10
2015 Population           NaN  3.017712e+06    NaN  ...  3.129950e+07
     GDP                  NaN  1.056140e+10    NaN  ...  6.673280e+10

country               Vanuatu  Venezuela, RB       Vietnam  \
year
1960 Population           NaN   8.146845e+06           NaN
     GDP                  NaN   8.607600e+09           NaN
1961 Population           NaN   8.461684e+06           NaN
     GDP                  NaN   8.923367e+09           NaN
1962 Population           NaN   8.790590e+06           NaN
...                       ...            ...           ...
2013 GDP         8.017876e+08   3.713366e+11  1.712220e+11
2014 Population  2.588830e+05            NaN  9.072890e+07
     GDP         8.149546e+08            NaN  1.862047e+11
2015 Population           NaN            NaN  9.170380e+07
     GDP                  NaN            NaN  1.935994e+11

country          Virgin Islands (U.S.)  West Bank and Gaza         World  \
year
1960 Population                32000.0                 NaN  3.035056e+09
     GDP                    24200000.0                 NaN  1.364643e+12
1961 Population                34100.0                 NaN  3.076121e+09
     GDP                    25700000.0                 NaN  1.420440e+12
1962 Population                36300.0                 NaN  3.129064e+09
...                                ...                 ...           ...
2013 GDP                           NaN        1.247600e+10  7.643132e+13
2014 Population                    NaN        4.294682e+06  7.260780e+09
     GDP                           NaN        1.271560e+10  7.810634e+13
2015 Population                    NaN        4.422143e+06  7.346633e+09
     GDP                           NaN        1.267740e+10  7.343364e+13

country           Yemen, Rep.        Zambia      Zimbabwe
year
1960 Population           NaN  3.049586e+06  3.752390e+06
     GDP                  NaN  6.987397e+08  1.052990e+09
1961 Population           NaN  3.142848e+06  3.876638e+06
     GDP                  NaN  6.823597e+08  1.096647e+09
1962 Population           NaN  3.240664e+06  4.006262e+06
...                       ...           ...           ...
2013 GDP         3.595450e+10  2.804552e+10  1.349023e+10
2014 Population           NaN  1.572134e+07  1.524586e+07
     GDP                  NaN  2.713464e+10  1.419691e+10
2015 Population           NaN  1.621177e+07  1.560275e+07
     GDP                  NaN  2.120156e+10  1.389294e+10

[112 rows x 252 columns]

In [ ]:
s.unstack(level = [0,1])
s.unstack(level = ['country','year'])

country       Arab World                                            \
year                2015          2014          2013          2012
Population  3.920223e+08  3.842226e+08  3.765043e+08  3.688026e+08
GDP         2.530102e+12  2.873600e+12  2.846994e+12  2.773270e+12

country                                                             \
year                2011          2010          2009          2008
Population  3.610318e+08  3.531122e+08  3.450542e+08  3.368865e+08
GDP         2.497945e+12  2.103825e+12  1.798878e+12  2.081343e+12

country                                 ...      Zimbabwe                \
year                2007          2006  ...          1969          1968
Population  3.287666e+08  3.209067e+08  ...  5.036321e+06  4.874113e+06
GDP         1.641666e+12  1.404190e+12  ...  1.747999e+09  1.479600e+09

country                                                             \
year                1967          1966          1965          1964
Population  4.718612e+06  4.568320e+06  4.422132e+06  4.279561e+06
GDP         1.397002e+09  1.281750e+09  1.311436e+09  1.217138e+09

country
year                1963          1962          1961          1960
Population  4.140804e+06  4.006262e+06  3.876638e+06  3.752390e+06
GDP         1.159512e+09  1.117602e+09  1.096647e+09  1.052990e+09

[2 rows x 11211 columns]

In [ ]:
s.unstack('year', fill_value = 0) #null value will be 0

year                            1960          1961          1962  \
country
Afghanistan Population  8.994793e+06  9.164945e+06  9.343772e+06
            GDP         5.377778e+08  5.488889e+08  5.466667e+08
Albania     Population  0.000000e+00  0.000000e+00  0.000000e+00
            GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria     Population  1.112489e+07  1.140486e+07  1.169015e+07
...                              ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia      Population  3.049586e+06  3.142848e+06  3.240664e+06
            GDP         6.987397e+08  6.823597e+08  6.792797e+08
Zimbabwe    Population  3.752390e+06  3.876638e+06  4.006262e+06
            GDP         1.052990e+09  1.096647e+09  1.117602e+09

year                            1963          1964          1965  \
country
Afghanistan Population  9.531555e+06  9.728645e+06  9.935358e+06
            GDP         7.511112e+08  8.000000e+08  1.006667e+09
Albania     Population  0.000000e+00  0.000000e+00  0.000000e+00
            GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria     Population  1.198513e+07  1.229597e+07  1.262695e+07
...                              ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia      Population  3.342894e+06  3.449266e+06  3.559687e+06
            GDP         7.043397e+08  8.226397e+08  1.061200e+09
Zimbabwe    Population  4.140804e+06  4.279561e+06  4.422132e+06
            GDP         1.159512e+09  1.217138e+09  1.311436e+09

year                            1966          1967          1968  \
country
Afghanistan Population  1.014884e+07  1.036860e+07  1.059979e+07
            GDP         1.400000e+09  1.673333e+09  1.373333e+09
Albania     Population  0.000000e+00  0.000000e+00  0.000000e+00
            GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria     Population  1.298027e+07  1.335420e+07  1.374438e+07
...                              ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia      Population  3.674088e+06  3.792864e+06  3.916928e+06
            GDP         1.239000e+09  1.340639e+09  1.573739e+09
Zimbabwe    Population  4.568320e+06  4.718612e+06  4.874113e+06
            GDP         1.281750e+09  1.397002e+09  1.479600e+09

year                            1969  ...          2006          2007  \
country                               ...
Afghanistan Population  1.084951e+07  ...  2.518362e+07  2.587754e+07
            GDP         1.408889e+09  ...  7.057598e+09  9.843842e+09
Albania     Population  0.000000e+00  ...  2.992547e+06  2.970017e+06
            GDP         0.000000e+00  ...  8.992642e+09  1.070101e+10
Algeria     Population  1.414444e+07  ...  3.374933e+07  3.426197e+07
...                              ...  ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  ...  1.908173e+10  2.563367e+10
Zambia      Population  4.047479e+06  ...  1.238151e+07  1.273868e+07
            GDP         1.926399e+09  ...  1.275686e+10  1.405696e+10
Zimbabwe    Population  5.036321e+06  ...  1.312794e+07  1.329780e+07
            GDP         1.747999e+09  ...  5.443896e+09  5.291950e+09

year                            2008          2009          2010  \
country
Afghanistan Population  2.652874e+07  2.720729e+07  2.796221e+07
            GDP         1.019053e+10  1.248694e+10  1.593680e+10
Albania     Population  2.947314e+06  2.927519e+06  2.913021e+06
            GDP         1.288135e+10  1.204421e+10  1.192695e+10
Algeria     Population  3.481106e+07  3.540179e+07  3.603616e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.039720e+10  2.845950e+10  3.090675e+10
Zambia      Population  1.311458e+07  1.350785e+07  1.391744e+07
            GDP         1.791086e+10  1.532834e+10  2.026555e+10
Zimbabwe    Population  1.349546e+07  1.372100e+07  1.397390e+07
            GDP         4.415703e+09  8.157077e+09  9.422161e+09

year                            2011          2012          2013  \
country
Afghanistan Population  2.880917e+07  2.972680e+07  3.068250e+07
            GDP         1.793024e+10  2.053654e+10  2.004633e+10
Albania     Population  2.904780e+06  2.900247e+06  2.896652e+06
            GDP         1.289087e+10  1.231978e+10  1.278103e+10
Algeria     Population  3.671713e+07  3.743943e+07  3.818614e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.107886e+10  3.207477e+10  3.595450e+10
Zambia      Population  1.434353e+07  1.478658e+07  1.524609e+07
            GDP         2.345952e+10  2.550306e+10  2.804552e+10
Zimbabwe    Population  1.425559e+07  1.456548e+07  1.489809e+07
            GDP         1.095623e+10  1.239272e+10  1.349023e+10

year                            2014          2015
country
Afghanistan Population  3.162751e+07  3.252656e+07
            GDP         2.005019e+10  1.919944e+10
Albania     Population  2.893654e+06  2.889167e+06
            GDP         1.327796e+10  1.145560e+10
Algeria     Population  3.893433e+07  3.966652e+07
...                              ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00
Zambia      Population  1.572134e+07  1.621177e+07
            GDP         2.713464e+10  2.120156e+10
Zimbabwe    Population  1.524586e+07  1.560275e+07
            GDP         1.419691e+10  1.389294e+10

[504 rows x 56 columns]