In [1]:
import pandas as pd

In [2]:
bigmac = pd.read_csv('csv_files/bigmac.csv', parse_dates=['Date'], date_format='%Y-%m-%d')
bigmac.head()

     Date    Country  Price in US Dollars
0  1/2016  Argentina                 2.39
1  1/2016  Australia                 3.74
2  1/2016     Brazil                 3.35
3  1/2016    Britain                 4.22
4  1/2016     Canada                 4.14

In [3]:
bigmac.set_index(keys=['Date', 'Country'], inplace=True) #outer layer should be the first, and larger should be second layer and so on

In [4]:
bigmac.sort_index(inplace=True)

In [5]:
type(bigmac.index)

pandas.MultiIndex

In [6]:
bigmac.index[0]

('1/2010', 'Argentina')

In [7]:
bigmac.index.get_level_values('Date')

Index(['1/2010', '1/2010', '1/2010', '1/2010', '1/2010', '1/2010', '1/2010',
       '1/2010', '1/2010', '1/2010',
       ...
       '7/2015', '7/2015', '7/2015', '7/2015', '7/2015', '7/2015', '7/2015',
       '7/2015', '7/2015', '7/2015'],
      dtype='str', name='Date', length=652)

In [8]:
bigmac.index.set_names(['Day', 'Location'], inplace=True)

In [9]:
bigmac.head()

                  Price in US Dollars
Day    Location
1/2010 Argentina                 1.84
       Australia                 3.98
       Brazil                    4.76
       Britain                   3.67
       Canada                    3.97

Extract Rows from MultiIndex

In [10]:
bigmac.loc[('1/2010', 'Brazil'), 'Price in US Dollars'] #key then the column value wanted to be extracted

np.float64(4.76)

In [11]:
bigmac = bigmac.transpose()

In [12]:
bigmac.loc['Price in US Dollars', ('1/2016', 'China')]

np.float64(2.68)

In [13]:
bigmac = pd.read_csv('csv_files/bigmac.csv', parse_dates=['Date'], date_format='%Y-%m-%d', index_col=['Date', 'Country'])
bigmac.sort_index(inplace=True)
bigmac.head()

                  Price in US Dollars
Date   Country
1/2010 Argentina                 1.84
       Australia                 3.98
       Brazil                    4.76
       Britain                   3.67
       Canada                    3.97

In [14]:
bigmac.swaplevel() #swaps index places

                      Price in US Dollars
Country       Date
Argentina     1/2010                 1.84
Australia     1/2010                 3.98
Brazil        1/2010                 4.76
Britain       1/2010                 3.67
Canada        1/2010                 3.97
...                                   ...
Ukraine       7/2015                 1.55
United States 7/2015                 4.79
Uruguay       7/2015                 4.13
Venezuela     7/2015                 0.67
Vietnam       7/2015                 2.75

[652 rows x 1 columns]