In [1]:
import pandas as pd

JOINS
![alt text](joins.png "Title")

In [2]:
week1 = pd.read_csv('csv_files/Restaurant - Week 1 Sales.csv')
week2 = pd.read_csv('csv_files/Restaurant - Week 2 Sales.csv')
customers = pd.read_csv('csv_files/Restaurant - Customers.csv')
foods = pd.read_csv('csv_files/Restaurant - Foods.csv')

In [3]:
print(f'week 1: {len(week1)}, week 2: {len(week2)}')

week 1: 250, week 2: 250

In [7]:
pd.concat([week1, week2], ignore_index= True)

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
495          783       10
496          556       10
497          547        9
498          252        9
499          249        6

[500 rows x 2 columns]

In [10]:
sales = pd.concat([week1, week2], keys=['A', 'B']) #even though the index are repeated another index is added A B.

In [ ]:
sales.loc[('A', 240)]

Customer ID    945
Food ID          5
Name: (A, 240), dtype: int64

In [14]:
sales.loc[('B', 240), 'Customer ID']

np.int64(734)

INNER JOIN

In [16]:
week1.merge(week2, how='inner', on='Customer ID')

    Customer ID  Food ID_x  Food ID_y
0           537          9          5
1           155          9          3
2           503          5          8
3           503          5          9
4           155          1          3
..          ...        ...        ...
57          945          5          4
58          343          3          5
59          343          3          2
60          343          3          7
61          621          9          6

[62 rows x 3 columns]

In [17]:
week1.merge(week2, how='inner', on='Customer ID', suffixes=['- Week 1', '- Week 2'])

    Customer ID  Food ID- Week 1  Food ID- Week 2
0           537                9                5
1           155                9                3
2           503                5                8
3           503                5                9
4           155                1                3
..          ...              ...              ...
57          945                5                4
58          343                3                5
59          343                3                2
60          343                3                7
61          621                9                6

[62 rows x 3 columns]

In [18]:
week1.merge(week2, how ='inner', on=['Customer ID', 'Food ID'])

   Customer ID  Food ID
0          304        3
1          540        3
2          937       10
3          233        3
4           21        4
5          922        1
6           21        4
7          578        5
8          578        5

In [19]:
week1[week1['Customer ID'] == 578]

     Customer ID  Food ID
224          578        5

In [20]:
week2[week2['Customer ID'] == 578]

     Customer ID  Food ID
29           578        5
189          578        5

In [24]:
merged = week1.merge(week2, how='outer', 
                     on='Customer ID', 
                     suffixes=['- Week 1', '- Week 2'], 
                     indicator= True)

In [26]:
merged['_merge'].value_counts()

_merge
right_only    197
left_only     195
both           62
Name: count, dtype: int64

In [29]:
mask = merged['_merge'].isin(['left_only', 'right_only'])
merged[mask]

     Customer ID  Food ID- Week 1  Food ID- Week 2      _merge
0              3              2.0              NaN   left_only
1              8              NaN              6.0  right_only
2             10              2.0              NaN   left_only
3             13              NaN              2.0  right_only
4             20              1.0              NaN   left_only
..           ...              ...              ...         ...
449          985              5.0              NaN   left_only
450          991              2.0              NaN   left_only
451          994              NaN              2.0  right_only
452          996              NaN             10.0  right_only
453         1000              2.0              NaN   left_only

[392 rows x 4 columns]

In [30]:
week1.head(3)

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1

In [31]:
foods.head(3)

   Food ID Food Item  Price
0        1     Sushi   3.99
1        2   Burrito   9.99
2        3      Taco   2.99

In [ ]:
week1 = week1.merge(foods, how='left', on='Food ID', sort=True) #sort sorts on Food ID

     Customer ID  Food ID Food Item  Price
0            658        1     Sushi   3.99
1            600        1     Sushi   3.99
2            155        1     Sushi   3.99
3            341        1     Sushi   3.99
4             20        1     Sushi   3.99
..           ...      ...       ...    ...
245          809       10     Drink   1.75
246          584       10     Drink   1.75
247          274       10     Drink   1.75
248          151       10     Drink   1.75
249          535       10     Drink   1.75

[250 rows x 4 columns]