In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('csv_files/employees.csv')
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    str
 2   Start Date         1000 non-null   str
 3   Last Login Time    1000 non-null   str
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    str
dtypes: float64(1), int64(1), object(1), str(5)
memory usage: 62.6+ KB

Optimization->

In [7]:
df['Start Date'] = pd.to_datetime(df["Start Date"])

In [9]:
df['Last Login Time'] = pd.to_datetime(df['Last Login Time'], format='%I:%M %p')

In [10]:
df['Senior Management'] = df['Senior Management'].astype('bool')

In [11]:
df['Gender'] = df['Gender'].astype('category')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    category
 2   Start Date         1000 non-null   datetime64[us]
 3   Last Login Time    1000 non-null   datetime64[us]
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    str
dtypes: bool(1), category(1), datetime64[us](2), float64(1), int64(1), str(2)
memory usage: 49.0 KB

Filter data

In [13]:
df['Gender'] == 'Male'

0       True
1       True
2      False
3       True
4       True
       ...
995    False
996     True
997     True
998     True
999     True
Name: Gender, Length: 1000, dtype: bool

In [14]:
df[df['Gender']=='Male']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2026-04-01 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,2026-04-01 06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,2026-04-01 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2026-04-01 16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,2026-04-01 01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,2026-04-01 17:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,2026-04-01 06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,2026-04-01 12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,2026-04-01 16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,2026-04-01 18:24:00,129949,10.169,True,Sales

In [16]:
df[df['Senior Management']]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2026-04-01 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,2026-04-01 06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,2026-04-01 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2026-04-01 16:47:00,101004,1.389,True,Client Services
6,Ruby,Female,1987-08-17,2026-04-01 16:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
991,Rose,Female,2002-08-25,2026-04-01 05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,2026-04-01 08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,2026-04-01 15:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,2026-04-01 17:47:00,98874,4.479,True,Marketing
999,Albert,Male,2012-05-15,2026-04-01 18:24:00,129949,10.169,True,Sales

In [18]:
mask = df['Bonus %'] < 1.5
df[mask]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
4,Larry,Male,1998-01-24,2026-04-01 16:47:00,101004,1.389,True,Client Services
15,Lillian,Female,2016-06-05,2026-04-01 06:09:00,59414,1.256,False,Product
58,Theresa,Female,2010-04-11,2026-04-01 07:18:00,72670,1.481,True,Engineering
77,Charles,Male,2004-09-14,2026-04-01 20:13:00,107391,1.260,True,Marketing
175,Willie,Male,1998-02-17,2026-04-01 20:20:00,146651,1.451,True,Engineering
189,Clarence,Male,1998-05-02,2026-04-01 03:16:00,85700,1.215,False,Sales
217,Douglas,Male,1999-09-03,2026-04-01 16:00:00,83341,1.015,True,Client Services
273,Nicholas,Male,1994-04-12,2026-04-01 20:21:00,74669,1.113,True,Product
279,Ruby,Female,2000-11-08,2026-04-01 19:35:00,105946,1.139,False,Business Development
365,Gloria,NaN,1983-07-19,2026-04-01 01:57:00,140885,1.113,False,Human Resources
445,Chris,Male,2006-12-12,2026-04-01 01:57:00,71642,1.496,False,NaN
481,NaN,Female,2013-04-27,2026-04-01 06:40:00,93847,1.085,True,Business Development
527,Helen,NaN,1993-12-02,2026-04-01 13:42:00,45724,1.022,False,Product
570,Kelly,Female,1996-08-16,2026-04-01 03:09:00,41427,1.431,False,Product
578,Amanda,Female,1982-03-17,2026-04-01 23:46:00,107111,1.438,True,Product
579,Harold,Male,2010-10-18,2026-04-01 20:45:00,65673,1.187,True,Legal
617,Kathy,Female,2001-01-14,2026-04-01 05:11:00,45682,1.451,True,Marketing
618,Peter,Male,1992-11-24,2026-04-01 17:43:00,69297,1.268,False,Finance
638,Frances,Female,1996-11-12,2026-04-01 18:08:00,112467,1.433,False,Business Development
652,Willie,Male,2009-12-05,2026-04-01 05:39:00,141932,1.017,True,Engineering
708,Steve,Male,2002-01-11,2026-04-01 21:17:00,51821,1.197,True,Legal
732,Henry,Male,1986-05-12,2026-04-01 02:04:00,59943,1.432,False,Finance
734,NaN,Female,1994-12-18,2026-04-01 20:42:00,138807,1.400,True,Human Resources
746,Gloria,Female,2004-08-19,2026-04-01 10:31:00,46602,1.027,True,Business Development
912,Joe,Male,1998-12-08,2026-04-01 10:28:00,126120,1.020,False,NaN
929,Theresa,Female,2001-04-27,2026-04-01 21:17:00,75661,1.079,True,Legal
954,Joe,Male,1980-01-19,2026-04-01 16:06:00,119667,1.148,True,Finance
997,Russell,Male,2013-05-20,2026-04-01 12:39:00,96914,1.421,False,Product

In [22]:
df[(df['Gender'] == 'Male') & (df['Team']=='Marketing')]
df[(df['Gender'] == 'Male') | (df['Team']=='Marketing')]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2026-04-01 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,2026-04-01 06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,2026-04-01 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2026-04-01 16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,2026-04-01 01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,2026-04-01 17:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,2026-04-01 06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,2026-04-01 12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,2026-04-01 16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,2026-04-01 18:24:00,129949,10.169,True,Sales

In [ ]:
#using isin for simpler filters
df[df['Team'].isin(['Legal', 'Sales', 'Product'])] #also can have series,list,tuples

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,2026-04-01 01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,2026-04-01 16:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,2026-04-01 15:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,2026-04-01 23:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,2026-04-01 06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,2026-04-01 17:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,2026-04-01 20:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,2026-04-01 16:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,2026-04-01 12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,2026-04-01 18:24:00,129949,10.169,True,Sales

In [26]:
df[df['Team'].isnull()]
df[df['Team'].notnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2026-04-01 12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,2026-04-01 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2026-04-01 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2026-04-01 16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,2026-04-01 01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,2026-04-01 06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,2026-04-01 06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,2026-04-01 12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,2026-04-01 16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,2026-04-01 18:24:00,129949,10.169,True,Sales

In [27]:
#inbetween

df[df['Salary'].between(60000, 70000)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,2026-04-01 06:53:00,61933,4.170,True,NaN
6,Ruby,Female,1987-08-17,2026-04-01 16:20:00,65476,10.012,True,Product
10,Louise,Female,1980-08-12,2026-04-01 09:01:00,63241,15.132,True,NaN
20,Lois,NaN,1995-04-22,2026-04-01 19:18:00,64714,4.934,True,Legal
41,Christine,NaN,2015-06-28,2026-04-01 01:08:00,66582,11.308,True,Business Development
...,...,...,...,...,...,...,...,...
965,Catherine,Female,1989-09-25,2026-04-01 01:31:00,68164,18.393,False,Client Services
970,Alice,Female,1988-09-03,2026-04-01 20:54:00,63571,15.397,True,Product
974,Harry,Male,2011-08-30,2026-04-01 18:31:00,67656,16.455,True,Client Services
978,Sean,Male,1983-01-17,2026-04-01 14:23:00,66146,11.178,False,Human Resources
998,Larry,Male,2013-04-20,2026-04-01 16:45:00,60500,11.985,False,Business Development

In [ ]:
#duplicate
df[df['First Name'].duplicated(keep='last')]
df[-df['First Name'].duplicated(keep=False)] # - is like not !

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,2026-04-01 01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,2026-04-01 06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,2026-04-01 09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,2026-04-01 03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,2026-04-01 10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,2026-04-01 10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,2026-04-01 22:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,2026-04-01 15:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,2026-04-01 08:48:00,92242,15.407,False,Legal

In [35]:
df.drop_duplicates(subset=['First Name'], keep= False)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,2026-04-01 01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,2026-04-01 06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,2026-04-01 09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,2026-04-01 03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,2026-04-01 10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,2026-04-01 10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,2026-04-01 22:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,2026-04-01 15:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,2026-04-01 08:48:00,92242,15.407,False,Legal

In [ ]:
#unique values
df['Team'].unique()
len(df['Team'].unique())

df['Team'].nunique(dropna= False) #counts only values that are not null adding dropna= False will reverse this feature

11