Pivot

In [5]:
import pandas as pd

In [9]:
sales = pd.read_csv('csv_files/salesmen.csv', parse_dates=['Date'])
sales['Salesman'] = sales['Salesman'].astype('category')
sales.head()

C:\Users\Softwel\AppData\Local\Temp\ipykernel_22724\3067540503.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales = pd.read_csv('csv_files/salesmen.csv', parse_dates=['Date'])

        Date Salesman  Revenue
0 2016-01-01      Bob     7172
1 2016-01-02      Bob     6362
2 2016-01-03      Bob     5982
3 2016-01-04      Bob     7917
4 2016-01-05      Bob     7837

In [10]:
sales.pivot(index = 'Date', columns="Salesman", values = 'Revenue')

Salesman     Bob  Dave   Jeb  Oscar  Ronald
Date
2016-01-01  7172  1864  4430   5250    2639
2016-01-02  6362  8278  8026   8661    4951
2016-01-03  5982  4226  5188   7075    2703
2016-01-04  7917  3868  3144   2524    4258
2016-01-05  7837  2287   938   2793    7771
...          ...   ...   ...    ...     ...
2016-12-27  2045  2843  6666    835    2981
2016-12-28   100  8888  1243   3073    6129
2016-12-29  4115  9490  3498   6424    7662
2016-12-30  2577  3594  8858   7088    2570
2016-12-31  3845  6830  9717   8408    2619

[366 rows x 5 columns]

In [11]:
foods = pd.read_csv('csv_files/foods.csv')
foods.head(3)

  First Name  Gender      City Frequency     Item  Spend
0      Wanda  Female  Stamford    Weekly   Burger  15.66
1       Eric    Male  Stamford     Daily  Chalupa  10.56
2    Charles    Male  New York     Never    Sushi  42.14

In [12]:
foods.pivot_table(values = 'Spend', index = 'Gender', aggfunc='mean')

            Spend
Gender
Female  50.709629
Male    49.397623

In [14]:
foods.pivot_table(values = 'Spend', index=['Gender', 'Item'], aggfunc='sum')

                    Spend
Gender Item
Female Burger     4094.30
       Burrito    4257.82
       Chalupa    4152.26
       Donut      4743.00
       Ice Cream  4032.87
       Sushi      4683.08
Male   Burger     3671.43
       Burrito    4012.62
       Chalupa    3492.26
       Donut      4015.76
       Ice Cream  4854.12
       Sushi      4059.85

In [ ]:
# foods.pivot_table(values = 'Spend', index=['Gender', 'Item'], columns=['Frequency', 'City'], aggfunc='sum')
foods.pivot_table(values = 'Spend', index=['Gender', 'Item'], columns='City', aggfunc='sum')

City              New York  Philadelphia  Stamford
Gender Item
Female Burger      1239.04       1639.24   1216.02
       Burrito      978.95       1458.76   1820.11
       Chalupa      876.58       1673.33   1602.35
       Donut       1446.78       1639.26   1656.96
       Ice Cream   1521.62       1479.22   1032.03
       Sushi       1480.29       1742.88   1459.91
Male   Burger      1294.09        938.18   1439.16
       Burrito     1399.40       1312.93   1300.29
       Chalupa     1227.77       1114.23   1150.26
       Donut       1345.27       1249.36   1421.13
       Ice Cream   1603.63       2191.27   1059.22
       Sushi       1396.15       1395.88   1267.82

In [19]:
pd.pivot_table(data = foods, values = 'Spend', index=['Gender', 'Item'], columns='City', aggfunc='sum')

City              New York  Philadelphia  Stamford
Gender Item
Female Burger      1239.04       1639.24   1216.02
       Burrito      978.95       1458.76   1820.11
       Chalupa      876.58       1673.33   1602.35
       Donut       1446.78       1639.26   1656.96
       Ice Cream   1521.62       1479.22   1032.03
       Sushi       1480.29       1742.88   1459.91
Male   Burger      1294.09        938.18   1439.16
       Burrito     1399.40       1312.93   1300.29
       Chalupa     1227.77       1114.23   1150.26
       Donut       1345.27       1249.36   1421.13
       Ice Cream   1603.63       2191.27   1059.22
       Sushi       1396.15       1395.88   1267.82